Update container
akanthas-lereacteur/akanthas_frontend_react pull request #26
Opened 2020-12-02 20:56 UTC by yayadiallo60

2020-12-02 21:02 UTC, MaloLebrin requested changes

2020-12-02 21:02 UTC, MaloLebrin commented on src/containers/UpdateContainer.js
> +  const [data, setData] = useState("");
tu es sur de toi ? sur. le state data en String vide ?

2020-12-02 21:22 UTC, yayadiallo60 commented on src/containers/UpdateContainer.js
> +  const [data, setData] = useState("");
ouai a 99,9% il prendra ce qu'on lui envoi

2020-12-03 08:52 UTC, nabil-ou approved these changes

2020-12-03 08:53 UTC, Mobu34 approved these changes

2020-12-03 08:54 UTC, merged